name: Lothario
favicon: null
layout_spectrum: 0.17704
typography_spectrum: 0.22037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00fff9'
    - '#ba8bfd'
    - '#fed5fd'
    - '#3607ab'
    - '#7842f2'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
